### ISSUE TITLE
PdfiumCore auto-generated bindings

### ISSUE THREAD

**Issue by Toumash** [huysentruitw/print-it#20]
Great project! The only one i on the web that makes it super easy to print pdfs on windows.

Question: Could we use the [PdfiumCore ](https://github.com/Dtronix/PDFiumCore) auto generated bindings instead of using pinvoked functions inside the print-it project?
I believe it would provide easier updates to the library.
Im working on a fork that would use them, but im not sure why it was not used originally - maybe you could help a little

The library has no `FPDF_RenderPage` anymore, but _[FPDF_RenderPageBitmap](https://github.com/Dtronix/PDFiumCore/blob/master/src/PDFiumCore/PDFiumCore.cs#L3229)_
Im struggling to convert it because _print-it_ uses `System.Drawing.Graphics` and the pdfium prints the pdf to `PdfiumCore.fpdfview.FpdfBitmapT`. I dont know easy way around it.
From what i understand if something about _Device-Dependent Bitmaps (DDBs)_ vs Independant ones  = bitmap vs HDC (?)

I dont expect full answer, but just a hint if you know how to approach it

**Comment by huysentruitw** [comment]
Why would you use those bindings? Perhaps they don't have the `FPDF_RenderPage` binding, because it is only included in the Windows build of Pdfium. The benifit of using `FPDF_RenderPage` is that we can directly render on a Windows Device Context (HDC) that we get from the Graphics object provided by Windows PrintPage event: https://github.com/huysentruitw/print-it/blob/5df7bffdd4460d17327794d9230bea9c4540e21e/src/PrintIt.Core/PdfPrintService.cs#L47

I think, going through a custom bitmap would require additional bit copying.

**Comment by huysentruitw** [comment]
In addition, this library is not meant to be cross-platform. I've built this out of frustration with other products, and thus it is meant to just work 🤣

**Comment by Toumash** [comment]
Oh yeah, i've just used your version. Should be fine 💪
